### PR TITLE
Workflow that deletes the PR dev space

### PR DESCRIPTION
**Pull request by greenie-msft**
Workflow that deletes the PR dev space when the PR closed

### CODE REVIEW

**Comment by greenie-msft** [comment]
@s-tuli Can you please review this PR.

**Comment by s-tuli** [comment]
@greenie-msft, could you look at the error on closePR?
There is an error for pr_closed.yml: "No event triggers defined in on"

**Comment by greenie-msft** [comment]
@s-tuli Addressed the issue that CTI reported. Should be good now?

**Comment by greenie-msft** [comment]
> Looks Good to me.
> Did you test it?

Yep, I did!

**Comment by s-tuli** [comment]
@greenie-msft, please feel free to merge! Thanks!

**Pull request merged**
